### ISSUE TITLE
I need help using this tool please


### ISSUE THREAD

**Issue by Jmoris100** [SMH17/bitcoin-hacking-tools#5]

**Comment by Gold-hurtur** [comment]
I really need to use it, tell me how

**Comment by Jmoris100** [comment]
Ok I'll help you

**Comment by Gold-hurtur** [comment]
Thanks bro

**Comment by Gold-hurtur** [comment]
Send me the settings please on this email
paulgoldnes@gmail.com

**Comment by Jmoris100** [comment]
You'll need to apply some funds

**Comment by Gold-hurtur** [comment]
Am ready

**Comment by VENOMGOD1** [comment]
Can you teach me on how to use this tool

**Comment by Gold-hurtur** [comment]
For sure this, guy doesn't have the tool.

**Comment by Gold-hurtur** [comment]
Your email

**Comment by VENOMGOD1** [comment]
Scottser31@gmail.com
